steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/jyotish-repo/jyotish-api', './api']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/jyotish-repo/jyotish-api']

# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jyotish-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/jyotish-repo/jyotish-api'
      - '--region'
      - 'europe-west10'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '40'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '50'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/jyotish-repo/jyotish-api'
options:
  logging: CLOUD_LOGGING_ONLY